version: '3.8'
services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/agrovision-app
    env_file:
      - ./frontend/agrovision-app/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
